export const navArr = ['ICON', 'Mac', 'iPad', 'iPhone', 'Watch', 'TV', 'Music', 'Support', 'ICON', 'ICON'];
export const subNavArr = [
  [null],
  ['MacBook Air', 'MacBook Pro', 'iMac', 'iMac Pro', 'Mac Pro', 'Mac mini', 'Compare', 'Pro Display XDR', 'Accessories', 'Mojave'],
  ['iPad Pro', 'iPad Air', 'iPad', 'iPad mini', 'Compare', 'Apple Pencil', 'Smart Keyboard', 'Accessories', 'iOS 12'],
  ['iPhone Xs', 'iPhone Xr', 'iPhone 8', 'iPhone 7', 'Compare', 'Apple Card', 'AirPods', 'Accessories', 'iOS 12'],
  ['Apple Watch Series 4', 'Apple Watch Nike+', 'Apple Watch Hermès', 'Apple Watch Series 3', 'watchOS', 'Bands', 'Accessories', 'Compare'],
  ['Apple TV App', 'Apple TV+', 'Apple TV 4K', 'Apple TV HD', 'AirPlay', 'Accessories'],
  ['Apple Music', 'iTunes', 'HomePod', 'AirPods', 'iPod touch', 'Music Accessories', 'Gift Cards'],
  [null],
  [null],
  [null]
]

export const urlArr = ['https://www.apple.com/ac/globalnav/4/en_US/images/globalnav/apple/image_large.svg', [null], [null], [null], [null], [null], [null], [null], 'https://www.apple.com/ac/globalnav/4/en_US/images/globalnav/search/image_large.svg', 'https://www.apple.com/ac/globalnav/4/en_US/images/globalnav/bag/image_large.svg',]
export const subUrlArr = [
  [null],
  ['https://www.apple.com/v/mac/home/ah/images/familybrowser/macbookair__ej39du0gz4uq_large.svg', 'https://www.apple.com/v/mac/home/ah/images/familybrowser/macbookpro__enfip2k1cxkm_large.svg', 'https://www.apple.com/v/mac/home/ah/images/familybrowser/imac__dkswmjfqeziq_large.svg', 'https://www.apple.com/v/mac/home/ah/images/familybrowser/imac_pro__eer4bfwlutme_large.svg', 'https://www.apple.com/v/mac/home/ah/images/familybrowser/mac_pro__bn92faz71k6a_large.svg', 'https://www.apple.com/v/mac/home/ah/images/familybrowser/macmini__c6u0it831y0y_large.svg', 'https://www.apple.com/v/mac/home/ah/images/familybrowser/mac_comp__ee2pokmcxh26_large.svg', 'https://www.apple.com/v/mac/home/ah/images/familybrowser/pro_display_xdr__do0vjpny1kqe_large.svg', 'https://www.apple.com/v/mac/home/ah/images/familybrowser/mac_acc__fy6vtx5eqoyi_large.svg', 'https://www.apple.com/v/mac/home/ah/images/familybrowser/mac_osx__dntc9ef2limq_large.svg'],
  ['https://www.apple.com/v/ipad/home/ar/images/chapternav/ipadpro_light__dxq7nxjgsd2e_large.svg', 'https://www.apple.com/v/ipad/home/ar/images/chapternav/ipadair_light__gan6yfrffc66_large.svg', 'https://www.apple.com/v/ipad/home/ar/images/chapternav/ipad_light__expohijp19si_large.svg', 'https://www.apple.com/v/ipad/home/ar/images/chapternav/ipadmini_light__bxpulkud30s2_large.svg', 'https://www.apple.com/v/ipad/home/ar/images/chapternav/ipad_comp_light__f80dzq6i8sq6_large.svg', 'https://www.apple.com/v/ipad/home/ar/images/chapternav/apple_pencil_light__e9zorbynwqie_large.svg', 'https://www.apple.com/v/ipad/home/ar/images/chapternav/keyboard_light__cjbr6d6i2vbm_large.svg', 'https://www.apple.com/v/ipad/home/ar/images/chapternav/ipad_acc_light__ebtftz3r2rwy_large.svg', 'https://www.apple.com/v/ipad/home/ar/images/chapternav/ios_light__d8hlu55ivueu_large.svg'],
  ['https://www.apple.com/v/iphone/home/aa/images/chapternav/iphonexs__haztskdvse62_large.svg', 'https://www.apple.com/v/iphone/home/aa/images/chapternav/iphonexr__dc5ls4xainsm_large.svg', 'https://www.apple.com/v/iphone/home/aa/images/chapternav/iphone8__ces17dqh6j6q_large.svg', 'https://www.apple.com/v/iphone/home/aa/images/chapternav/iphone7__ew0p3ahbemuu_large.svg', 'https://www.apple.com/v/iphone/home/aa/images/chapternav/compare__fx9dq75qwnma_large.svg', 'https://www.apple.com/v/iphone/home/aa/images/chapternav/applecard__gip86jgm8zee_large.svg', 'https://www.apple.com/v/iphone/home/aa/images/chapternav/airpods__c6lrgkbcjdg2_large.svg', 'https://www.apple.com/v/iphone/home/aa/images/chapternav/accessories__bfu76z4hzusy_large.svg', 'https://www.apple.com/v/iphone/home/aa/images/chapternav/ios__btf1uz0f3d0i_large.svg'],
  ['https://www.apple.com/v/watch/home/q/images/overview/watch_nav_series_2__bk595ih4bliu_large.svg', 'https://www.apple.com/v/watch/home/q/images/overview/watch_nav_nike__mkjgkrrlq2ye_large.svg', 'https://www.apple.com/v/watch/home/q/images/overview/watch_nav_hermes__b1zeoxbn0df6_large.svg', 'https://www.apple.com/v/watch/home/q/images/overview/watch_nav_edition__botzv6l1ftua_large.svg', 'https://www.apple.com/v/watch/home/q/images/overview/watch_nav_watch_os__fctkp231ik6e_large.svg', 'https://www.apple.com/v/watch/home/q/images/overview/watch_nav_bands__f5qi8icu6suq_large.svg', 'https://www.apple.com/v/watch/home/q/images/overview/watch_nav_accessories__fix8lwwxvtu2_large.svg', 'https://www.apple.com/v/watch/home/q/images/overview/watch_nav_compare__bjddtmfseahe_large.svg'],
  ['https://www.apple.com/v/tv/home/g/images/home/apple_tv_app_dark__blle10nnpq3m_large.svg', 'https://www.apple.com/v/tv/home/g/images/home/apple_tv_plus_dark__fntbqaxjuouy_large.svg', 'https://www.apple.com/v/tv/home/g/images/home/apple_tv_dark__ern1bz8tkwqe_large.svg', 'https://www.apple.com/v/tv/home/g/images/home/apple_tv_dark__ern1bz8tkwqe_large.svg', 'https://www.apple.com/v/tv/home/g/images/home/airplay_dark__dqiw3rzeujma_large.svg', 'https://www.apple.com/v/tv/home/g/images/home/accessories_dark__dybfk40y28om_large.svg'],
  ['https://www.apple.com/v/music/h/images/overview/icons/apple_music_large.svg', 'https://www.apple.com/v/music/h/images/overview/icons/itunes_large.svg', 'https://www.apple.com/v/music/h/images/overview/icons/homepod_icon_large.svg', 'https://www.apple.com/v/music/h/images/overview/icons/airpods_icon_large.svg', 'https://www.apple.com/v/music/h/images/overview/icons/ipod_touch_light_large.svg', 'https://www.apple.com/v/music/h/images/overview/icons/accessories_large.svg', 'https://www.apple.com/v/music/h/images/overview/icons/gift_cards_large.svg'],
  [null],
  [null],
  [null]
]